### PR TITLE
Untested fix to allow Ethernet connectivity

### PR DESCRIPTION
**Pull request by LawnGnome**
At present, CheapCast only works if the Android device is using wi-fi for its network connectivity. This means that CheapCast can't be used on devices such as an Ouya if they're plugged into an Ethernet connection.

This PR theoretically fixes this. Unfortunately, I can't figure out how to compile CheapCast to actually test it, but I've tried the heuristic in the PR in a standalone app and it seems to detect the right address on both my phone and my Ouya. (It probably won't work properly on the ATV1200 I have floating around, since that has both Ethernet and wi-fi active at once, but one problem at a time.)

This may require some massaging before it's releasable, but the approach is sound. This would fix issue #8.

### CODE REVIEW

**Comment by mauimauer** [comment]
I'll test this ASAP

**Comment by lanrat** [comment]
I believe this is the same issue preventing cheapcast from working on some of the Google TVs.
Cheapcast works fine on my Logitech Revue when on WIFI, but it is undiscoverable on ethernet .

**Comment by kaazvaag** [comment]
Does the ethernet fix work? And is it implemented in the new beta?

**Comment by LawnGnome** [comment]
I've now been able to build this and test it, and it does seem to work fine on both my Ouya (with a wired connection) and my phone (on wifi).

**Comment by mauimauer** [comment]
Going to release a new version to the store today

**Comment by lanrat** [comment]
This fixed the issue with using Ethernet on the Revue!

**Comment by kaazvaag** [comment]
Nice fix. It works on the Minix X5.

**Comment by clercqer** [comment]
Cheapcast still does not work when I connect my MK809III to my LAN through an USB-to-ethernet adapter. I checked the URLbase and it reports the correct IP.

Can someone help me solve the issue?

**Pull request merged**
